import { writeStore } from './store.js';

const now = new Date('2026-06-16T15:00:00.000Z').toISOString();

const professors = [
  {
    id: 'prof-anita-rao',
    email: 'anita-rao@andrew.cmu.edu',
    name: 'Dr. Anita Rao',
    department: 'Machine Learning Department',
    title: 'Associate Professor',
    officeHours: 'Tue 2-4 PM, Gates 8013',
    bioUrl: 'https://www.ml.cmu.edu/people/faculty/rao.html',
    researchAreas: ['Machine Learning', 'Healthcare AI'],
    researchInterests: ['Interpretable machine learning', 'Clinical decision support', 'Model evaluation'],
    lab: 'Trustworthy Health ML Lab',
    publications: 7,
    presentations: 9,
    grantFunding: '$710K',
  },
  {
    id: 'prof-benjamin-kline',
    email: 'benjamin-kline@andrew.cmu.edu',
    name: 'Dr. Benjamin Kline',
    department: 'Robotics Institute',
    title: 'Assistant Professor',
    officeHours: 'Wed 10-12 PM, Newell-Simon 3212',
    bioUrl: 'https://www.ri.cmu.edu/ri-faculty/benjamin-kline',
    researchAreas: ['Robotics', 'Autonomous Systems'],
    researchInterests: ['Navigation', 'Multi-robot planning', 'Dynamic environments'],
    lab: 'Field Robotics Navigation Group',
    publications: 8,
    presentations: 11,
    grantFunding: '$840K',
  },
  {
    id: 'prof-elena-watson',
    email: 'elena-watson@andrew.cmu.edu',
    name: 'Dr. Elena Watson',
    department: 'Computer Science Department',
    title: 'Professor',
    officeHours: 'Thu 1-3 PM, Gates 7115',
    bioUrl: 'https://www.cs.cmu.edu/directory/elena-watson',
    researchAreas: ['Natural Language Processing', 'Human-AI Collaboration'],
    researchInterests: ['LLM research assistants', 'Literature review systems', 'AI evaluation'],
    lab: 'AI Research Systems Lab',
    publications: 6,
    presentations: 8,
    grantFunding: '$620K',
  },
  {
    id: 'prof-marcus-lee',
    email: 'marcus-lee@andrew.cmu.edu',
    name: 'Dr. Marcus Lee',
    department: 'Biomedical Engineering',
    title: 'Associate Professor',
    officeHours: 'Mon 3-5 PM, Scott Hall 4211',
    bioUrl: 'https://www.bme.cmu.edu/directory/marcus-lee',
    researchAreas: ['Biomedical Engineering', 'Computer Vision'],
    researchInterests: ['Medical imaging', 'Signal processing', 'Clinical translation'],
    lab: 'Health Data Science Lab',
    publications: 7,
    presentations: 8,
    grantFunding: '$760K',
  },
  {
    id: 'prof-priya-shah',
    email: 'priya-shah@andrew.cmu.edu',
    name: 'Dr. Priya Shah',
    department: 'Tepper School of Business',
    title: 'Assistant Professor',
    officeHours: 'Fri 9-11 AM, Tepper 5220',
    bioUrl: 'https://www.cmu.edu/tepper/faculty-and-research/faculty-by-area/profiles/shah-priya.html',
    researchAreas: ['Business Analytics', 'Economics'],
    researchInterests: ['Market risk', 'Student success analytics', 'Operations research'],
    lab: 'AI + Business Research Group',
    publications: 5,
    presentations: 9,
    grantFunding: '$590K',
  },
  {
    id: 'prof-lina-huang',
    email: 'lina-huang@andrew.cmu.edu',
    name: 'Dr. Lina Huang',
    department: 'Electrical and Computer Engineering',
    title: 'Associate Professor',
    officeHours: 'Tue 11-1 PM, Hamerschlag B120',
    bioUrl: 'https://www.ece.cmu.edu/directory/bios/huang-lina.html',
    researchAreas: ['Electrical & Computer Engineering', 'Signal Processing'],
    researchInterests: ['Brain-computer interfaces', 'Edge ML', 'Wearable sensing'],
    lab: 'Embedded Intelligence Lab',
    publications: 4,
    presentations: 6,
    grantFunding: '$420K',
  },
  {
    id: 'prof-owen-bradford',
    email: 'owen-bradford@andrew.cmu.edu',
    name: 'Dr. Owen Bradford',
    department: 'Heinz College of Information Systems and Public Policy',
    title: 'Professor',
    officeHours: 'Wed 2-4 PM, Hamburg Hall 2117',
    bioUrl: 'https://www.heinz.cmu.edu/faculty-research/profiles/bradford-owen',
    researchAreas: ['Public Policy', 'Climate Analytics'],
    researchInterests: ['Climate policy', 'Causal inference', 'Public-sector data'],
    lab: 'Computational Policy Lab',
    publications: 6,
    presentations: 7,
    grantFunding: '$510K',
  },
  {
    id: 'prof-natalie-cho',
    email: 'natalie-cho@andrew.cmu.edu',
    name: 'Dr. Natalie Cho',
    department: 'Psychology Department',
    title: 'Assistant Professor',
    officeHours: 'Thu 10-12 PM, Baker Hall 340A',
    bioUrl: 'https://www.cmu.edu/dietrich/psychology/people/faculty/cho-natalie.html',
    researchAreas: ['Psychology', 'Behavioral Economics'],
    researchInterests: ['Decision making', 'Cognitive science', 'Human-AI teams'],
    lab: 'Behavior and Decision Lab',
    publications: 4,
    presentations: 7,
    grantFunding: '$310K',
  },
];

const students = [
  ['student-maya-patel', 'Maya Patel', 'maya-patel@andrew.cmu.edu', 'Computer Science', 'Junior', '2027', 3.87, ['Python', 'ROS', 'C++', 'OpenCV', 'PyTorch'], ['Robotics', 'Computer Vision', 'Multi-Agent Systems'], 95],
  ['student-jonathan-youngblood', 'Jonathan Youngblood', 'jonathan-youngblood@andrew.cmu.edu', 'Business Administration', 'Sophomore', '2028', 3.74, ['Python', 'SQL', 'Tableau', 'Power BI', 'PyTorch'], ['Machine Learning', 'Business Analytics', 'AI for Business'], 92],
  ['student-elena-garcia', 'Elena Garcia', 'elena-garcia@andrew.cmu.edu', 'Statistics & Machine Learning', "Master's", '2026', 3.91, ['R', 'Python', 'SQL', 'CausalML', 'ggplot2'], ['Health AI', 'Causal Inference', 'Data Visualization'], 89],
  ['student-noah-kim', 'Noah Kim', 'noah-kim@andrew.cmu.edu', 'Electrical & Computer Engineering', 'Junior', '2027', 3.62, ['C', 'Python', 'MATLAB', 'TensorFlow Lite', 'Linux'], ['Embedded AI', 'Signal Processing', 'Edge Computing'], 84],
  ['student-aisha-robinson', 'Aisha Robinson', 'aisha-robinson@andrew.cmu.edu', 'Public Policy', "Master's", '2026', 3.83, ['R', 'Python', 'GIS', 'Policy Writing', 'Causal Inference'], ['Climate Policy', 'Causal Inference', 'Equity Analytics'], 88],
  ['student-samir-mehta', 'Samir Mehta', 'samir-mehta@andrew.cmu.edu', 'Cognitive Science', 'Senior', '2026', 3.69, ['User Research', 'Python', 'Qualtrics', 'Thematic Coding', 'Statistics'], ['Human-AI Collaboration', 'Psychology', 'Education Technology'], 86],
  ['student-grace-liu', 'Grace Liu', 'grace-liu@andrew.cmu.edu', 'Biology', 'Junior', '2027', 3.58, ['Python', 'ImageJ', 'CellProfiler', 'Pandas', 'Lab Protocols'], ['Biomedical Engineering', 'Medical Imaging', 'Computational Biology'], 81],
  ['student-diego-martinez', 'Diego Martinez', 'diego-martinez@andrew.cmu.edu', 'Mechanical Engineering', 'Sophomore', '2028', 3.44, ['MATLAB', 'Python', 'Arduino', 'CAD', 'Controls'], ['Robotics', 'Controls', 'Human-Robot Interaction'], 76],
  ['student-sophia-nguyen', 'Sophia Nguyen', 'sophia-nguyen@andrew.cmu.edu', 'Economics', 'Senior', '2026', 3.78, ['R', 'Stata', 'Python', 'Regression', 'Research Writing'], ['Behavioral Economics', 'Financial Markets', 'Decision Making'], 87],
  ['student-ethan-brooks', 'Ethan Brooks', 'ethan-brooks@andrew.cmu.edu', 'Computer Science', "Master's", '2026', 3.94, ['Python', 'PyTorch', 'Transformers', 'Evaluation', 'Elasticsearch'], ['Natural Language Processing', 'Information Retrieval', 'LLM Evaluation'], 96],
  ['student-leah-cohen', 'Leah Cohen', 'leah-cohen@andrew.cmu.edu', 'Statistics & Machine Learning', 'Junior', '2027', 3.88, ['R', 'Python', 'Scikit-learn', 'Fairness Metrics', 'SQL'], ['Student Success Analytics', 'Predictive Modeling', 'Fairness'], 91],
  ['student-arjun-iyer', 'Arjun Iyer', 'arjun-iyer@andrew.cmu.edu', 'Electrical & Computer Engineering', "Master's", '2026', 3.9, ['Python', 'MATLAB', 'EEG', 'Signal Processing', 'Scikit-learn'], ['Brain-Computer Interfaces', 'Signal Processing', 'Biomedical Devices'], 94],
  ['student-nina-okafor', 'Nina Okafor', 'nina-okafor@andrew.cmu.edu', 'Public Policy', 'Senior', '2026', 3.71, ['Python', 'GIS', 'Policy Memos', 'Data Cleaning'], ['Climate Analytics', 'Public Sector Data', 'Equity'], 82],
  ['student-owen-wilson', 'Owen Wilson', 'owen-wilson@andrew.cmu.edu', 'Business Administration', 'Junior', '2027', 3.55, ['Python', 'SQL', 'Tableau', 'Time Series', 'Excel'], ['Business Analytics', 'Financial Risk', 'Operations'], 79],
  ['student-camila-torres', 'Camila Torres', 'camila-torres@andrew.cmu.edu', 'Psychology', 'Junior', '2027', 3.67, ['R', 'Qualtrics', 'Survey Design', 'Thematic Coding'], ['Behavioral Economics', 'Decision Making', 'Survey Research'], 85],
  ['student-victor-chen', 'Victor Chen', 'victor-chen@andrew.cmu.edu', 'Computer Science', 'Senior', '2026', 3.82, ['Python', 'PyTorch', 'OpenCV', 'CUDA', 'Experiment Tracking'], ['Computer Vision', 'Medical Imaging', 'Deep Learning'], 93],
  ['student-hana-kobayashi', 'Hana Kobayashi', 'hana-kobayashi@andrew.cmu.edu', 'Machine Learning', 'PhD', '2029', 4.0, ['Python', 'PyTorch', 'Calibration', 'SHAP', 'Causal Inference'], ['Interpretable ML', 'Healthcare AI', 'Fairness'], 98],
  ['student-lucas-brown', 'Lucas Brown', 'lucas-brown@andrew.cmu.edu', 'Statistics & Machine Learning', 'Sophomore', '2028', 3.51, ['R', 'Python', 'Tableau', 'Data Cleaning'], ['Predictive Analytics', 'Education Data', 'Visualization'], 74],
  ['student-rachel-stein', 'Rachel Stein', 'rachel-stein@andrew.cmu.edu', 'Cognitive Science', 'Senior', '2026', 3.76, ['User Research', 'Figma', 'Python', 'Interview Coding', 'Statistics'], ['Human-AI Collaboration', 'Education Technology', 'UX Research'], 90],
  ['student-kevin-park', 'Kevin Park', 'kevin-park@andrew.cmu.edu', 'Mechanical Engineering', "Master's", '2026', 3.73, ['Python', 'C++', 'ROS', 'Optimization', 'Simulation'], ['Robotics', 'Planning', 'Controls'], 88],
  ['student-mina-haddad', 'Mina Haddad', 'mina-haddad@andrew.cmu.edu', 'Economics', "Master's", '2026', 3.86, ['Python', 'R', 'Time Series', 'Econometrics', 'SQL'], ['Financial Risk', 'Causal Inference', 'Market Design'], 92],
  ['student-tyler-evans', 'Tyler Evans', 'tyler-evans@andrew.cmu.edu', 'Business Administration', 'Sophomore', '2028', 3.35, ['Excel', 'SQL', 'Tableau', 'Python'], ['Student Success Analytics', 'Operations Research'], 68],
  ['student-isabel-rivera', 'Isabel Rivera', 'isabel-rivera@andrew.cmu.edu', 'Biology', 'Senior', '2026', 3.61, ['R', 'Python', 'Lab Protocols', 'Clinical Labels'], ['Biomedical Engineering', 'Healthcare AI', 'Clinical Data'], 77],
  ['student-david-ross', 'David Ross', 'david-ross@andrew.cmu.edu', 'Computer Science', 'First-Year', '2029', 3.7, ['Python', 'JavaScript', 'React', 'Data Visualization'], ['Machine Learning', 'Education Technology'], 66],
  ['student-megan-foster', 'Megan Foster', 'megan-foster@andrew.cmu.edu', 'Public Policy', 'Junior', '2027', 3.42, ['R', 'Survey Design', 'Policy Writing', 'Data Cleaning'], ['Climate Policy', 'Behavioral Economics'], 72],
];

const projectSeeds = [
  ['project-health-ml', 'prof-anita-rao', 'Machine Learning', 'Interpretable Machine Learning for Healthcare', 'Develop explanation and calibration workflows for clinical risk models using de-identified health data.', ['Interpretable ML', 'Healthcare AI'], ['Python', 'PyTorch', 'Model Evaluation', 'Statistics'], '10-12 hours per week', '2026-07-15', '2026-08-24', '2 semesters', 'stipend'],
  ['project-robot-nav', 'prof-benjamin-kline', 'Robotics', 'Robotics Navigation in Dynamic Environments', 'Build navigation policies that remain robust when people and obstacles move unpredictably.', ['Navigation', 'Autonomous Systems'], ['Python', 'C++', 'ROS', 'Planning'], '12-15 hours per week', '2026-07-12', '2026-08-24', '2 semesters', 'stipend'],
  ['project-llm-lit-review', 'prof-elena-watson', 'Computer Science', 'LLM-Based Research Assistant for Literature Review', 'Prototype and evaluate an LLM assistant that helps researchers find, cluster, and summarize related work.', ['NLP', 'Human-AI Collaboration'], ['Python', 'Transformers', 'Information Retrieval', 'Evaluation'], '8-12 hours per week', '2026-07-18', '2026-08-24', '1 semester', 'course credit'],
  ['project-student-success', 'prof-priya-shah', 'Business Analytics', 'Predictive Analytics for Student Success', 'Create early-warning models and dashboards for student support interventions while auditing fairness.', ['Predictive Analytics', 'Education Data'], ['SQL', 'Python', 'Statistics', 'Dashboarding'], '8-10 hours per week', '2026-07-20', '2026-08-24', '1 semester', 'course credit'],
  ['project-market-risk', 'prof-priya-shah', 'Economics', 'Financial Market Risk Modeling', 'Stress-test portfolio risk models across volatility regimes using market and macroeconomic data.', ['Financial Markets', 'Risk Modeling'], ['Python', 'R', 'Time Series', 'Econometrics'], '10-12 hours per week', '2026-07-22', '2026-08-24', '1 semester', 'stipend'],
  ['project-medical-vision', 'prof-marcus-lee', 'Biomedical Engineering', 'Computer Vision for Medical Imaging', 'Train and evaluate image models for segmentation and quality control in clinical imaging workflows.', ['Computer Vision', 'Medical Imaging'], ['Python', 'PyTorch', 'OpenCV', 'Image Analysis'], '10-14 hours per week', '2026-07-16', '2026-08-24', '2 semesters', 'stipend'],
  ['project-human-ai-ed', 'prof-elena-watson', 'Psychology', 'Human-AI Collaboration in Education', 'Study when AI-generated hints improve learning and when they create overreliance.', ['Human-AI Collaboration', 'Education Technology'], ['User Research', 'Python', 'Statistics', 'Study Design'], '8-10 hours per week', '2026-07-24', '2026-08-24', '1 semester', 'course credit'],
  ['project-climate-policy', 'prof-owen-bradford', 'Public Policy', 'Climate Policy Data Analysis', 'Analyze whether municipal climate programs reduce energy burden across neighborhoods.', ['Climate Policy', 'Causal Inference'], ['R', 'Python', 'GIS', 'Policy Writing'], '8-12 hours per week', '2026-07-19', '2026-08-24', '1 semester', 'stipend'],
  ['project-behavioral-econ', 'prof-natalie-cho', 'Economics', 'Behavioral Economics and Decision Making', 'Run survey and lab studies on how people make decisions under uncertainty and time pressure.', ['Behavioral Economics', 'Decision Making'], ['R', 'Survey Design', 'Statistics', 'Research Writing'], '6-9 hours per week', '2026-07-25', '2026-08-24', '1 semester', 'volunteer'],
  ['project-bci-signal', 'prof-lina-huang', 'Electrical & Computer Engineering', 'Brain-Computer Interface Signal Processing', 'Improve EEG feature extraction and classification pipelines for motor-imagery BCI experiments.', ['Brain-Computer Interfaces', 'Signal Processing'], ['MATLAB', 'Python', 'Signal Processing', 'EEG'], '10-12 hours per week', '2026-07-14', '2026-08-24', '2 semesters', 'stipend'],
  ['project-edge-wearables', 'prof-lina-huang', 'Electrical & Computer Engineering', 'Edge ML for Wearable Health Sensors', 'Benchmark activity-recognition models for low-power wearable devices.', ['Embedded AI', 'Wearable Sensing'], ['C', 'Python', 'TensorFlow Lite', 'Linux'], '9-12 hours per week', '2026-07-26', '2026-08-24', '1 semester', 'stipend'],
  ['project-grasp-planning', 'prof-benjamin-kline', 'Robotics', 'Perception-Driven Grasp Planning', 'Use 3D perception to improve grasp success in cluttered tabletop scenes.', ['Manipulation', 'Computer Vision'], ['Python', 'C++', '3D Geometry', 'Simulation'], '10-14 hours per week', '2026-07-17', '2026-08-24', '1 semester', 'stipend'],
];

const users = [
  ...professors.map((professor) => ({
    id: professor.id,
    email: professor.email,
    name: professor.name,
    role: 'professor',
    createdAt: now,
  })),
  ...students.map(([id, name, email]) => ({
    id,
    email,
    name,
    role: 'student',
    createdAt: now,
  })),
  {
    id: 'dean-demo',
    email: 'dean.demo@andrew.cmu.edu',
    name: 'CMU Dean Demo',
    role: 'dean',
    createdAt: now,
  },
  {
    id: 'recruiter-demo',
    email: 'recruiter.demo@andrew.cmu.edu',
    name: 'CMU Recruiter Demo',
    role: 'recruiter',
    createdAt: now,
  },
];

const professorProfiles = professors.map((professor) => ({
  id: `profile-${professor.id}`,
  userId: professor.id,
  department: professor.department,
  title: professor.title,
  contactEmail: professor.email,
  officeHours: professor.officeHours,
  bioUrl: professor.bioUrl,
  researchAreas: professor.researchAreas,
  researchInterests: professor.researchInterests,
  professorWebsite: `https://cmu-demo.example.edu/${professor.lab.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  publicationsLink: `https://scholar.google.com/citations?user=${professor.id}`,
  researchSummary: `${professor.lab} mentors students on ${professor.researchInterests.join(', ')} with ${professor.publications} recent publications, ${professor.presentations} presentations, and ${professor.grantFunding} in active funding.`,
  photoBase64: '',
  lab: professor.lab,
  publications: professor.publications,
  presentations: professor.presentations,
  grantFunding: professor.grantFunding,
}));

const studentProfiles = students.map(([id, name, email, major, year, graduationYear, gpa, skills, interests, confidenceScore]) => ({
  id: `profile-${id}`,
  userId: id,
  name,
  email,
  major,
  graduationYear,
  academicYear: year,
  gpa,
  skills,
  interests,
  bio: `${year} ${major} student interested in ${interests.slice(0, 2).join(' and ')} with evidence-backed skills in ${skills.slice(0, 3).join(', ')}.`,
  resume: {
    name: `${name.toLowerCase().replace(/[^a-z0-9]+/g, '_')}_research_resume.pdf`,
    uploadDate: now,
  },
  sourceTags: ['resume', 'github', 'linkedin', 'coursework'],
  githubUrl: `https://github.com/${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  portfolioUrl: `https://portfolio.example.edu/${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  linkedinUrl: `https://linkedin.com/in/${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  confidenceScore,
  matchReasons: [
    `Direct overlap with ${interests[0]}`,
    `Evidence-backed ${skills[0]} experience`,
    confidenceScore >= 88 ? 'Strong prior research signal' : 'Good growth profile with scoped mentorship',
  ],
  evidenceItems: [
    {
      type: 'github_repo',
      title: `${name.split(' ')[0].toLowerCase()}-research-portfolio`,
      url: `https://github.com/cmu-demo/${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-research`,
    },
    {
      type: 'research_report',
      title: `${name.split(' ')[0]} research summary`,
      url: `https://cmu-demo.example.edu/evidence/${id}-summary.pdf`,
    },
  ],
  photoBase64: '',
}));

const postings = projectSeeds.map(([id, professorId, category, title, overview, researchAreas, skillsNeeded, timeCommitmentExpected, applicationDeadline, startDate, duration, compensation], index) => {
  const professor = professors.find((entry) => entry.id === professorId);

  return {
    id,
    professorId,
    professorName: professor.name,
    professorEmail: professor.email,
    professorBioUrl: professor.bioUrl,
    professorDepartment: professor.department,
    professorResearchAreas: professor.researchAreas,
    professorResearchInterests: professor.researchInterests,
    category,
    researchAreas,
    skillsNeeded,
    title,
    overview,
    studentRoleDescription: 'Contribute to weekly lab deliverables, maintain reproducible research artifacts, and present findings during mentor check-ins.',
    studentGain: 'Faculty mentorship, portfolio-ready evidence, research communication practice, and exposure to publication-oriented workflows.',
    requiredQualifications: skillsNeeded.slice(0, 2).join(', '),
    preferredQualifications: skillsNeeded.slice(2).join(', ') || 'Prior research experience',
    timeCommitmentExpected,
    startDate,
    duration,
    applicationDeadline,
    compensation,
    questions: [
      {
        question: `Why are you interested in ${title}?`,
        wordLimit: 150,
      },
      {
        question: `Which prior project best shows your readiness for ${category} research?`,
        wordLimit: 150,
      },
    ],
    quickNoteEnabled: true,
    createdAt: new Date(Date.UTC(2026, 4, index + 1, 14, 0, 0)).toISOString(),
    status: 'published',
    locations: ['Gates Hillman Center', 'Newell-Simon Hall', 'Tepper Quad', 'Hamburg Hall', 'Hybrid'],
    difficultyLevel: index % 3 === 0 ? 'Advanced' : index % 3 === 1 ? 'Intermediate' : 'Beginner-friendly',
    openPositions: index % 4 === 0 ? 3 : 2,
  };
});

const store = {
  users,
  postings,
  studentProfiles,
  professorProfiles,
};

writeStore(store);
console.log(`Seed complete: server/data/store.json (${postings.length} postings, ${studentProfiles.length} students, ${professorProfiles.length} professors)`);
