-- Adds demo research opportunities to the exact table loaded by the UI.
-- UI path: DataProvider.refreshProjects -> listPublicProjects -> public.projects
-- Visibility condition: status = 'published'.
-- Existing valid professor owner observed in the configured Supabase project:
--   0d3faeef-6723-4937-86c2-ea378e6d694a

insert into public.projects (
  id,
  professor_id,
  category,
  research_areas,
  skills_needed,
  title,
  overview,
  student_role_description,
  student_gain,
  required_qualifications,
  preferred_qualifications,
  time_commitment_expected,
  start_date,
  duration,
  application_deadline,
  compensation,
  questions,
  quick_note_enabled,
  status,
  approved_at
)
values
  (
    '10000000-0000-4000-8000-000000000001',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Machine Learning',
    array['Interpretable ML', 'Healthcare AI'],
    array['Python', 'PyTorch', 'Statistics', 'Model Evaluation'],
    'Interpretable Machine Learning for Healthcare',
    'Develop explanation and calibration workflows for clinical risk models using de-identified health data.',
    'Run model audits, write analysis notebooks, and prepare weekly summaries for the research team.',
    'Experience with responsible AI evaluation, clinical ML workflows, and publication-quality research communication.',
    'Python, statistics, and machine learning coursework.',
    'PyTorch, calibration metrics, or healthcare data experience.',
    '10-12 hours per week',
    '2026-09-01',
    '2 semesters',
    '2026-09-15',
    'stipend',
    '[{"question":"Describe a model evaluation project you have completed.","wordLimit":150},{"question":"How would you explain uncertainty to a clinical stakeholder?","wordLimit":150}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000002',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Robotics',
    array['Navigation', 'Autonomous Systems'],
    array['Python', 'C++', 'ROS', 'Planning'],
    'Robotics Navigation in Dynamic Environments',
    'Build navigation policies that remain robust when people and obstacles move unpredictably.',
    'Implement simulation scenarios, evaluate planners, and help collect robot telemetry.',
    'Hands-on robotics research experience with planning, simulation, and safety evaluation.',
    'Algorithms, Python, and linear algebra.',
    'ROS, C++, motion planning, or robotics lab experience.',
    '12-15 hours per week',
    '2026-09-01',
    '2 semesters',
    '2026-09-15',
    'stipend',
    '[{"question":"What makes navigation difficult in dynamic scenes?","wordLimit":140},{"question":"Describe your robotics or simulation experience.","wordLimit":140}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000003',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Computer Science',
    array['NLP', 'Human-AI Collaboration'],
    array['Python', 'Transformers', 'Information Retrieval', 'Evaluation'],
    'LLM-Based Literature Review Assistant',
    'Prototype and evaluate an LLM assistant that helps researchers find, cluster, and summarize related work.',
    'Build retrieval pipelines, evaluate summaries, and design study materials for lab users.',
    'Applied NLP systems experience and exposure to human-centered AI evaluation.',
    'Python and data structures.',
    'NLP coursework, search systems, or LLM evaluation experience.',
    '8-12 hours per week',
    '2026-09-01',
    '1 semester',
    '2026-09-15',
    'course credit',
    '[{"question":"How would you evaluate a literature-review assistant?","wordLimit":150},{"question":"What risks appear when summarizing papers with LLMs?","wordLimit":150}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000004',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Business Analytics',
    array['Predictive Analytics', 'Education Data'],
    array['SQL', 'Python', 'Statistics', 'Dashboarding'],
    'Predictive Analytics for Student Success',
    'Create early-warning models and dashboards for student support interventions while auditing fairness.',
    'Clean advising datasets, train baselines, and summarize model risks for program leaders.',
    'Portfolio-ready analytics experience with ethical data-use framing.',
    'Statistics and SQL fundamentals.',
    'Fairness metrics, Tableau, or education analytics experience.',
    '8-10 hours per week',
    '2026-09-01',
    '1 semester',
    '2026-09-15',
    'course credit',
    '[{"question":"What features might predict student success without becoming unfair?","wordLimit":150}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000005',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Economics',
    array['Financial Markets', 'Risk Modeling'],
    array['Python', 'R', 'Time Series', 'Econometrics'],
    'Financial Market Risk Modeling',
    'Stress-test portfolio risk models across volatility regimes using market and macroeconomic data.',
    'Build reproducible notebooks, compare VaR variants, and document assumptions.',
    'Experience connecting economics, statistical modeling, and decision-ready visualizations.',
    'Probability, regression, and coding basics.',
    'Time-series modeling, finance coursework, or risk dashboards.',
    '10-12 hours per week',
    '2026-09-01',
    '1 semester',
    '2026-09-15',
    'stipend',
    '[{"question":"Describe a financial or time-series analysis you have done.","wordLimit":140}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000006',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Biomedical Engineering',
    array['Computer Vision', 'Medical Imaging'],
    array['Python', 'PyTorch', 'OpenCV', 'Image Analysis'],
    'Computer Vision for Medical Imaging',
    'Train and evaluate image models for segmentation and quality control in clinical imaging workflows.',
    'Prepare datasets, run baseline experiments, and create error-analysis reports.',
    'Medical imaging research experience with model training and translational constraints.',
    'Python and linear algebra.',
    'Computer vision, PyTorch, or biomedical domain experience.',
    '10-14 hours per week',
    '2026-09-01',
    '2 semesters',
    '2026-09-15',
    'stipend',
    '[{"question":"What failure modes matter in medical imaging models?","wordLimit":150}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000007',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Psychology',
    array['Human-AI Collaboration', 'Education Technology'],
    array['User Research', 'Python', 'Statistics', 'Study Design'],
    'Human-AI Collaboration in Education',
    'Study when AI-generated hints improve learning and when they create overreliance.',
    'Instrument prototypes, analyze interaction logs, and help run user studies.',
    'End-to-end human-centered AI research practice.',
    'Research methods and comfort with data analysis.',
    'HCI, psychology, or education technology research experience.',
    '8-10 hours per week',
    '2026-09-01',
    '1 semester',
    '2026-09-15',
    'course credit',
    '[{"question":"How would you identify overreliance on AI hints?","wordLimit":150}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000008',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Public Policy',
    array['Climate Policy', 'Causal Inference'],
    array['R', 'Python', 'GIS', 'Policy Writing'],
    'Climate Policy Data Analysis',
    'Analyze whether municipal climate programs reduce energy burden across neighborhoods.',
    'Clean public datasets, estimate policy effects, and draft policy-facing visuals.',
    'Policy analytics portfolio evidence and applied causal inference experience.',
    'Data cleaning and policy writing.',
    'GIS, causal inference, or climate policy background.',
    '8-12 hours per week',
    '2026-09-01',
    '1 semester',
    '2026-09-15',
    'stipend',
    '[{"question":"How would you communicate uncertainty in a policy memo?","wordLimit":140}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000009',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Economics',
    array['Behavioral Economics', 'Decision Making'],
    array['R', 'Survey Design', 'Statistics', 'Research Writing'],
    'Behavioral Economics and Decision Making',
    'Run survey and lab studies on how people make decisions under uncertainty and time pressure.',
    'Code survey responses, run statistical models, and produce study documentation.',
    'Behavioral research methods, data analysis, and faculty-reviewed contribution evidence.',
    'Statistics and careful written communication.',
    'Qualtrics, R, or behavioral economics coursework.',
    '6-9 hours per week',
    '2026-09-01',
    '1 semester',
    '2026-09-15',
    'volunteer',
    '[{"question":"Describe a behavioral study design you find convincing.","wordLimit":140}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000010',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Electrical & Computer Engineering',
    array['Brain-Computer Interfaces', 'Signal Processing'],
    array['MATLAB', 'Python', 'Signal Processing', 'EEG'],
    'Brain-Computer Interface Signal Processing',
    'Improve EEG feature extraction and classification pipelines for motor-imagery BCI experiments.',
    'Implement filters, compare classifiers, and package reproducible reports.',
    'Signal processing and biomedical device research experience.',
    'Signals and systems plus Python or MATLAB.',
    'EEG, wearable sensing, or ML classification experience.',
    '10-12 hours per week',
    '2026-09-01',
    '2 semesters',
    '2026-09-15',
    'stipend',
    '[{"question":"What signal-processing steps would you use before classification?","wordLimit":150}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000011',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Electrical & Computer Engineering',
    array['Smart Grids', 'Optimization'],
    array['Python', 'Convex Optimization', 'Power Systems', 'Simulation'],
    'Optimization Methods for Smart Grids',
    'Model demand-response strategies and optimize energy dispatch for campus-scale smart-grid scenarios.',
    'Implement optimization baselines, run simulations, and summarize tradeoffs for grid operators.',
    'Experience with optimization, energy systems, and reproducible simulation workflows.',
    'Python and linear algebra.',
    'Convex optimization, power systems, or simulation experience.',
    '9-12 hours per week',
    '2026-09-01',
    '1 semester',
    '2026-09-15',
    'tbd',
    '[{"question":"What tradeoffs matter in grid optimization?","wordLimit":140}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000012',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Statistics & Data Science',
    array['Public Health', 'Data Visualization'],
    array['R', 'D3', 'Statistics', 'Data Storytelling'],
    'Data Visualization for Public Health',
    'Create visual analytics for regional public-health indicators and uncertainty-aware communication.',
    'Prepare datasets, build dashboard prototypes, and evaluate interpretability with stakeholders.',
    'Applied data-visualization experience with public-health impact.',
    'Statistics and data cleaning.',
    'D3, R Shiny, public-health data, or visual design.',
    '8-10 hours per week',
    '2026-09-01',
    '1 semester',
    '2026-09-15',
    'course credit',
    '[{"question":"How would you visualize uncertainty for nontechnical audiences?","wordLimit":140}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000013',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Computer Science',
    array['AI Safety', 'Evaluation'],
    array['Python', 'LLM Evaluation', 'Benchmarking', 'Statistics'],
    'AI Safety Evaluation Benchmarks',
    'Design benchmark tasks for measuring reliability, refusal behavior, and robustness in AI assistants.',
    'Write benchmark prompts, analyze model outputs, and document evaluation limitations.',
    'Practical AI safety evaluation and research-methods experience.',
    'Python and careful experimental design.',
    'LLM evaluation, statistics, or responsible AI coursework.',
    '8-12 hours per week',
    '2026-09-01',
    '1 semester',
    '2026-09-15',
    'stipend',
    '[{"question":"What makes an AI safety benchmark trustworthy?","wordLimit":150}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000014',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Biomedical Engineering',
    array['Biomedical Signals', 'Wearable Sensing'],
    array['Python', 'MATLAB', 'Signal Processing', 'Pandas'],
    'Biomedical Signal Processing',
    'Process noisy wearable-sensor data to identify clinically meaningful movement and physiology features.',
    'Build preprocessing notebooks, compare feature pipelines, and validate data-quality flags.',
    'Biomedical analytics experience with signal processing and reproducible reporting.',
    'Signals, Python, and data analysis.',
    'Wearable sensing, MATLAB, or biomedical datasets.',
    '10-12 hours per week',
    '2026-09-01',
    '2 semesters',
    '2026-09-15',
    'stipend',
    '[{"question":"How would you handle noisy wearable-sensor data?","wordLimit":140}]'::jsonb,
    true,
    'published',
    now()
  ),
  (
    '10000000-0000-4000-8000-000000000015',
    '0d3faeef-6723-4937-86c2-ea378e6d694a',
    'Statistics & Data Science',
    array['Higher Education Analytics', 'Causal Inference'],
    array['SQL', 'Python', 'R', 'Fairness Metrics'],
    'Undergraduate Research Participation Analytics',
    'Analyze participation trends, barriers, and outcomes in undergraduate research access across departments.',
    'Clean participation datasets, estimate access gaps, and prepare faculty-facing analytics briefs.',
    'Institutional analytics experience with equity, outcomes, and research-program strategy.',
    'SQL, statistics, and communication skills.',
    'Causal inference, dashboarding, or higher-education data experience.',
    '8-10 hours per week',
    '2026-09-01',
    '1 semester',
    '2026-09-15',
    'course credit',
    '[{"question":"What signals would you use to measure equitable research access?","wordLimit":150}]'::jsonb,
    true,
    'published',
    now()
  )
on conflict (id) do update set
  professor_id = excluded.professor_id,
  category = excluded.category,
  research_areas = excluded.research_areas,
  skills_needed = excluded.skills_needed,
  title = excluded.title,
  overview = excluded.overview,
  student_role_description = excluded.student_role_description,
  student_gain = excluded.student_gain,
  required_qualifications = excluded.required_qualifications,
  preferred_qualifications = excluded.preferred_qualifications,
  time_commitment_expected = excluded.time_commitment_expected,
  start_date = excluded.start_date,
  duration = excluded.duration,
  application_deadline = excluded.application_deadline,
  compensation = excluded.compensation,
  questions = excluded.questions,
  quick_note_enabled = excluded.quick_note_enabled,
  status = excluded.status,
  approved_at = excluded.approved_at,
  updated_at = now();

notify pgrst, 'reload schema';
