export type ResearchSubjectGroup = {
  title: string;
  subjects: string[];
};

export const RESEARCH_SUBJECT_GROUPS: ResearchSubjectGroup[] = [
  {
    "title": "Computer Science",
    "subjects": [
      "Algorithms & Data Structures",
      "Quantum Computing",
      "Artificial Intelligence",
      "Cloud Computing",
      "Machine Learning",
      "Parallel & High-Performance Computing",
      "Deep Learning",
      "Theoretical Computer Science",
      "Natural Language Processing",
      "Computational Complexity",
      "Computer Vision",
      "Formal Methods & Verification",
      "Robotics",
      "Computer Graphics",
      "Human-Computer Interaction",
      "Virtual & Augmented Reality",
      "Operating Systems",
      "Bioinformatics & Computational Biology",
      "Computer Networks",
      "Information Retrieval",
      "Distributed Systems",
      "Recommender Systems",
      "Database Systems",
      "Embedded Systems",
      "Software Engineering",
      "Internet of Things (IoT)",
      "Programming Languages & Compilers",
      "Edge Computing",
      "Computer Architecture",
      "Blockchain & Distributed Ledger",
      "Cybersecurity & Cryptography",
      "Data Science & Big Data"
    ]
  },
  {
    "title": "Mathematics",
    "subjects": [
      "Algebra",
      "Mathematical Statistics",
      "Linear Algebra",
      "Stochastic Processes",
      "Abstract Algebra",
      "Numerical Analysis",
      "Number Theory",
      "Optimization Theory",
      "Calculus & Real Analysis",
      "Game Theory",
      "Complex Analysis",
      "Mathematical Logic",
      "Functional Analysis",
      "Set Theory",
      "Differential Equations (ODEs & PDEs)",
      "Category Theory",
      "Topology",
      "Dynamical Systems & Chaos Theory",
      "Differential Geometry",
      "Information Theory",
      "Algebraic Geometry",
      "Cryptography (Mathematical)",
      "Discrete Mathematics",
      "Actuarial Mathematics",
      "Combinatorics",
      "Financial Mathematics",
      "Graph Theory",
      "Operations Research",
      "Probability Theory"
    ]
  },
  {
    "title": "Physics",
    "subjects": [
      "Classical Mechanics",
      "Plasma Physics",
      "Electromagnetism",
      "Optics & Photonics",
      "Thermodynamics & Statistical Mechanics",
      "Acoustics",
      "Quantum Mechanics",
      "Biophysics",
      "Quantum Field Theory",
      "Medical Physics",
      "Relativity (Special & General)",
      "Computational Physics",
      "Particle Physics",
      "Atomic & Molecular Physics",
      "Nuclear Physics",
      "Geophysics",
      "Condensed Matter Physics",
      "Fluid Mechanics",
      "Astrophysics",
      "String Theory & M-Theory",
      "Cosmology"
    ]
  },
  {
    "title": "Chemistry",
    "subjects": [
      "Organic Chemistry",
      "Electrochemistry",
      "Inorganic Chemistry",
      "Surface Chemistry",
      "Physical Chemistry",
      "Supramolecular Chemistry",
      "Analytical Chemistry",
      "Chemical Engineering",
      "Biochemistry",
      "Environmental Chemistry",
      "Computational Chemistry",
      "Atmospheric Chemistry",
      "Polymer Chemistry",
      "Astrochemistry",
      "Green Chemistry",
      "Organometallic Chemistry",
      "Medicinal Chemistry",
      "Materials Chemistry",
      "Nuclear Chemistry",
      "Food Chemistry"
    ]
  },
  {
    "title": "Biology",
    "subjects": [
      "Cell Biology",
      "Bioinformatics",
      "Molecular Biology",
      "Marine Biology",
      "Genetics",
      "Zoology",
      "Genomics & Proteomics",
      "Botany",
      "Evolutionary Biology",
      "Mycology",
      "Ecology",
      "Physiology",
      "Microbiology",
      "Anatomy",
      "Virology",
      "Biochemistry",
      "Immunology",
      "Astrobiology",
      "Neuroscience",
      "Conservation Biology",
      "Developmental Biology",
      "Parasitology",
      "Structural Biology",
      "Paleontology",
      "Systems Biology",
      "Epigenetics"
    ]
  },
  {
    "title": "Medicine & Health Sciences",
    "subjects": [
      "Anatomy & Physiology",
      "Endocrinology",
      "Pathology",
      "Nephrology",
      "Pharmacology",
      "Pulmonology",
      "Internal Medicine",
      "Rheumatology",
      "Surgery",
      "Obstetrics & Gynecology",
      "Neurology",
      "Immunology (Clinical)",
      "Oncology",
      "Medical Genetics",
      "Cardiology",
      "Public Health & Epidemiology",
      "Infectious Disease",
      "Biomedical Engineering",
      "Psychiatry",
      "Physical Therapy & Rehabilitation",
      "Pediatrics",
      "Dentistry",
      "Geriatrics",
      "Veterinary Medicine",
      "Radiology & Imaging",
      "Palliative Care",
      "Emergency Medicine",
      "Nutrition & Dietetics",
      "Anesthesiology",
      "Sports Medicine",
      "Dermatology",
      "Toxicology",
      "Ophthalmology",
      "Forensic Medicine"
    ]
  },
  {
    "title": "Engineering",
    "subjects": [
      "Mechanical Engineering",
      "Nuclear Engineering",
      "Electrical Engineering",
      "Industrial & Systems Engineering",
      "Civil Engineering",
      "Robotics Engineering",
      "Chemical Engineering",
      "Automotive Engineering",
      "Aerospace & Aeronautical Engineering",
      "Ocean & Marine Engineering",
      "Biomedical Engineering",
      "Petroleum Engineering",
      "Environmental Engineering",
      "Mining Engineering",
      "Computer Engineering",
      "Agricultural Engineering",
      "Software Engineering",
      "Architectural Engineering",
      "Structural Engineering",
      "Photonics Engineering",
      "Geotechnical Engineering",
      "Nano-engineering",
      "Transportation Engineering",
      "Energy Engineering",
      "Materials Engineering"
    ]
  },
  {
    "title": "Economics",
    "subjects": [
      "Microeconomics",
      "Industrial Organization",
      "Macroeconomics",
      "Game Theory (Economic)",
      "Econometrics",
      "Monetary Economics",
      "Behavioral Economics",
      "Political Economy",
      "Development Economics",
      "Urban & Regional Economics",
      "International Economics & Trade",
      "Agricultural Economics",
      "Labor Economics",
      "Economic History",
      "Public Economics",
      "Welfare Economics",
      "Health Economics",
      "Experimental Economics",
      "Environmental & Ecological Economics",
      "Computational Economics",
      "Financial Economics"
    ]
  },
  {
    "title": "Psychology",
    "subjects": [
      "Clinical Psychology",
      "Organizational & Industrial Psychology",
      "Cognitive Psychology",
      "Experimental Psychology",
      "Developmental Psychology",
      "Psychometrics",
      "Social Psychology",
      "Positive Psychology",
      "Neuropsychology",
      "Evolutionary Psychology",
      "Personality Psychology",
      "Cross-Cultural Psychology",
      "Forensic Psychology",
      "Abnormal Psychology",
      "Health Psychology",
      "Counseling Psychology",
      "Educational Psychology",
      "Sports Psychology"
    ]
  },
  {
    "title": "Sociology",
    "subjects": [
      "Social Theory",
      "Medical Sociology",
      "Demography & Population Studies",
      "Political Sociology",
      "Criminology",
      "Sociology of Religion",
      "Social Stratification",
      "Environmental Sociology",
      "Sociology of Education",
      "Globalization",
      "Urban Sociology",
      "Social Movements",
      "Rural Sociology",
      "Sociology of Work",
      "Gender Studies",
      "Cultural Sociology",
      "Race & Ethnic Studies",
      "Family Studies"
    ]
  },
  {
    "title": "Political Science",
    "subjects": [
      "Comparative Politics",
      "Constitutional Law",
      "International Relations",
      "Human Rights",
      "Political Theory & Philosophy",
      "Conflict & Peace Studies",
      "Public Policy & Administration",
      "Geopolitics",
      "Electoral Studies",
      "Political Sociology",
      "Political Economy",
      "Environmental Politics",
      "Security Studies",
      "Global Governance",
      "Diplomacy & Foreign Policy"
    ]
  },
  {
    "title": "Anthropology",
    "subjects": [
      "Cultural Anthropology",
      "Urban Anthropology",
      "Physical/Biological Anthropology",
      "Cognitive Anthropology",
      "Archaeology",
      "Forensic Anthropology",
      "Linguistic Anthropology",
      "Environmental Anthropology",
      "Medical Anthropology",
      "Visual Anthropology",
      "Economic Anthropology",
      "Applied Anthropology"
    ]
  },
  {
    "title": "History",
    "subjects": [
      "Ancient History",
      "Political History",
      "Medieval History",
      "Art History",
      "Modern History",
      "Religious History",
      "Contemporary History",
      "Environmental History",
      "Military History",
      "Oral History",
      "Economic History",
      "Historiography",
      "Social History",
      "History of Medicine",
      "Cultural History",
      "World History",
      "History of Science & Technology",
      "Regional History"
    ]
  },
  {
    "title": "Philosophy",
    "subjects": [
      "Metaphysics",
      "Philosophy of Mathematics",
      "Epistemology",
      "Philosophy of Religion",
      "Ethics & Moral Philosophy",
      "Philosophy of Law",
      "Logic",
      "Existentialism",
      "Philosophy of Mind",
      "Phenomenology",
      "Philosophy of Science",
      "Analytic Philosophy",
      "Political Philosophy",
      "Continental Philosophy",
      "Aesthetics",
      "Applied Ethics",
      "Philosophy of Language"
    ]
  },
  {
    "title": "Linguistics",
    "subjects": [
      "Phonetics & Phonology",
      "Historical & Comparative Linguistics",
      "Morphology",
      "Discourse Analysis",
      "Syntax",
      "Applied Linguistics",
      "Semantics",
      "Sign Language Studies",
      "Pragmatics",
      "Language Acquisition",
      "Sociolinguistics",
      "Corpus Linguistics",
      "Psycholinguistics",
      "Neurolinguistics",
      "Computational Linguistics"
    ]
  },
  {
    "title": "Education & Pedagogy",
    "subjects": [
      "Curriculum Theory & Design",
      "Educational Technology",
      "Educational Psychology",
      "Educational Policy",
      "Special Education",
      "Adult & Lifelong Learning",
      "Higher Education",
      "Distance & Online Education",
      "Early Childhood Education",
      "Multicultural Education",
      "STEM Education",
      "Mathematics Education",
      "Language Education (TESOL/EFL)",
      "Science Education",
      "Comparative Education",
      "Assessment & Measurement"
    ]
  },
  {
    "title": "Arts & Humanities",
    "subjects": [
      "Literature & Literary Theory",
      "Creative Writing",
      "Visual Arts",
      "Digital Humanities",
      "Music Theory & Musicology",
      "Classics & Classical Studies",
      "Performing Arts",
      "Religious Studies",
      "Film Studies",
      "Gender & Sexuality Studies",
      "Theatre Studies",
      "African Studies",
      "Art History",
      "Asian Studies",
      "Cultural Studies",
      "Latin American Studies",
      "Media Studies",
      "Middle Eastern Studies",
      "Rhetoric & Composition"
    ]
  },
  {
    "title": "Law",
    "subjects": [
      "Constitutional Law",
      "Labor & Employment Law",
      "Criminal Law",
      "Family Law",
      "Civil Law",
      "Administrative Law",
      "International Law",
      "Comparative Law",
      "Human Rights Law",
      "Cyber Law",
      "Intellectual Property Law",
      "Maritime Law",
      "Environmental Law",
      "Health Law",
      "Corporate & Commercial Law",
      "Immigration Law",
      "Tax Law"
    ]
  },
  {
    "title": "Business & Management",
    "subjects": [
      "Accounting",
      "International Business",
      "Finance",
      "Business Ethics",
      "Marketing",
      "Project Management",
      "Organizational Behavior",
      "Innovation Management",
      "Strategic Management",
      "Corporate Governance",
      "Entrepreneurship",
      "E-commerce",
      "Operations Management",
      "Real Estate",
      "Supply Chain Management",
      "Hospitality Management",
      "Human Resource Management",
      "Healthcare Management"
    ]
  },
  {
    "title": "Environmental Science",
    "subjects": [
      "Ecology",
      "Environmental Chemistry",
      "Climate Science",
      "Environmental Policy",
      "Atmospheric Science",
      "Conservation Science",
      "Oceanography",
      "Sustainability Science",
      "Hydrology",
      "Soil Science",
      "Geology",
      "Remote Sensing & GIS",
      "Geochemistry",
      "Natural Hazards",
      "Glaciology",
      "Environmental Toxicology"
    ]
  },
  {
    "title": "Astronomy & Space Science",
    "subjects": [
      "Observational Astronomy",
      "Extragalactic Astronomy",
      "Astrophysics",
      "Radio Astronomy",
      "Cosmology",
      "Gravitational Wave Astronomy",
      "Planetary Science",
      "Solar Physics",
      "Astrobiology",
      "Space Exploration & Astronautics",
      "Stellar Astrophysics",
      "Exoplanet Science",
      "Galactic Astronomy"
    ]
  },
  {
    "title": "Neuroscience",
    "subjects": [
      "Cognitive Neuroscience",
      "Neuroimaging",
      "Computational Neuroscience",
      "Neurophysiology",
      "Molecular & Cellular Neuroscience",
      "Neuroethics",
      "Systems Neuroscience",
      "Developmental Neuroscience",
      "Behavioral Neuroscience",
      "Neurogenetics",
      "Clinical Neuroscience",
      "Neuropsychopharmacology"
    ]
  },
  {
    "title": "Materials Science",
    "subjects": [
      "Nanomaterials",
      "Electronic Materials",
      "Biomaterials",
      "Superconductors",
      "Polymers",
      "2D Materials (Graphene etc.)",
      "Semiconductors",
      "Smart Materials",
      "Ceramics",
      "Energy Materials",
      "Metals & Alloys",
      "Computational Materials Science",
      "Composites"
    ]
  },
  {
    "title": "Geography",
    "subjects": [
      "Physical Geography",
      "GIS & Cartography",
      "Human Geography",
      "Biogeography",
      "Urban Geography",
      "Climatology",
      "Economic Geography",
      "Geomorphology",
      "Political Geography",
      "Population Geography",
      "Cultural Geography",
      "Development Geography",
      "Historical Geography"
    ]
  },
  {
    "title": "Communication & Media Studies",
    "subjects": [
      "Mass Communication",
      "Science Communication",
      "Journalism",
      "Health Communication",
      "Public Relations",
      "Organizational Communication",
      "Advertising",
      "Intercultural Communication",
      "Digital Media",
      "Media Ethics",
      "Social Media Studies",
      "Data Journalism",
      "Film & Television Studies"
    ]
  },
  {
    "title": "Statistics & Data Science",
    "subjects": [
      "Mathematical Statistics",
      "Statistical Learning",
      "Bayesian Statistics",
      "Causal Inference",
      "Applied Statistics",
      "Data Mining",
      "Statistical Inference",
      "Data Visualization",
      "Multivariate Analysis",
      "Big Data Analytics",
      "Time Series Analysis",
      "Biostatistics",
      "Survival Analysis",
      "Psychometrics",
      "Spatial Statistics",
      "Experimental Design"
    ]
  },
  {
    "title": "Agriculture & Food Science",
    "subjects": [
      "Agronomy",
      "Agricultural Economics",
      "Horticulture",
      "Agricultural Engineering",
      "Animal Science",
      "Sustainable Agriculture",
      "Aquaculture",
      "Agroforestry",
      "Food Technology & Processing",
      "Viticulture & Enology",
      "Soil Science",
      "Nutrition Science",
      "Plant Pathology",
      "Food Safety & Quality"
    ]
  },
  {
    "title": "Architecture & Urban Planning",
    "subjects": [
      "Architectural Design",
      "Interior Architecture",
      "Structural Design",
      "Historic Preservation",
      "Sustainable Architecture",
      "Housing Studies",
      "Urban Design",
      "Smart Cities",
      "Urban Planning",
      "Transport Planning",
      "Landscape Architecture",
      "Regional Planning"
    ]
  },
  {
    "title": "Information Science & Library Science",
    "subjects": [
      "Information Architecture",
      "Information Behavior",
      "Knowledge Management",
      "Scientometrics & Bibliometrics",
      "Digital Libraries",
      "Ontologies & Taxonomies",
      "Archival Science",
      "Records Management",
      "Metadata & Cataloging",
      "Open Access & Scholarly Communication"
    ]
  },
  {
    "title": "Religious Studies & Theology",
    "subjects": [
      "Comparative Religion",
      "Ethics & Religion",
      "Christian Theology",
      "Philosophy of Religion",
      "Islamic Studies",
      "History of Religion",
      "Jewish Studies",
      "Mysticism",
      "Buddhist Studies",
      "Sociology of Religion",
      "Hindu Studies",
      "Religious Education"
    ]
  },
  {
    "title": "Cognitive Science",
    "subjects": [
      "Cognitive Psychology",
      "Artificial Intelligence (Cognitive)",
      "Computational Modeling",
      "Perception & Attention",
      "Cognitive Linguistics",
      "Memory & Learning",
      "Cognitive Neuroscience",
      "Decision Making",
      "Philosophy of Mind",
      "Consciousness Studies"
    ]
  },
  {
    "title": "Energy Science & Engineering",
    "subjects": [
      "Renewable Energy (Solar, Wind, Hydro)",
      "Energy Policy",
      "Nuclear Energy",
      "Energy Economics",
      "Energy Storage",
      "Thermodynamics (Applied)",
      "Smart Grids",
      "Fuel Cells & Hydrogen Energy",
      "Fossil Fuels & Combustion",
      "Energy Efficiency"
    ]
  },
  {
    "title": "Security Studies",
    "subjects": [
      "Cybersecurity",
      "Conflict Resolution",
      "National Security",
      "Arms Control & Non-proliferation",
      "Intelligence Studies",
      "Critical Infrastructure Protection",
      "Counter-terrorism",
      "Biosecurity",
      "Military Science",
      "Nuclear Security"
    ]
  }
];
